version: '3'
services:
    influxdb:
        image: 'influxdb:latest'
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
    garie-sentry-metrics:
        image: 'garie-sentry-metrics:latest'
        privileged: true
        volumes:
            - /usr/local/bin/docker:/bin/docker
        ports:
            - 3000:3000
        environment:
            - HOST=influxdb
            - SENTRY_AUTHORIZATION=
            - MATOMO_TOKEN=
            - REPORT_DIR
        depends_on:
            - influxdb
    chronograf:
        image: 'chronograf:latest'
        ports:
            - 8888:8888
        depends_on:
            - influxdb
